# Generated by Django 4.1 on 2022-12-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images')),
                ('descripcion', models.TextField(default='Sin descripción', max_length=320)),
                ('stock', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
