# Generated by Django 4.1.2 on 2022-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto1', models.CharField(max_length=50)),
                ('producto2', models.CharField(max_length=50)),
                ('producto3', models.CharField(max_length=50)),
                ('nombreCombo', models.CharField(max_length=50)),
                ('precioCombo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=50)),
                ('nombreTipo', models.CharField(choices=[('H', 'Hamburguesa'), ('C', 'Completo'), ('P', 'Pizza '), ('PF', 'Papas Fritas'), ('J', 'Jugo'), ('B', 'Bebida')], default='H', max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10)),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('Cargo', models.CharField(choices=[('C', 'Cajero'), ('G', 'Gestor de Reportes'), ('A', 'Administrador')], default='C', max_length=1)),
                ('Contrato', models.CharField(choices=[('P', 'Plazo Fijo'), ('I', 'Indefinido')], default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('nombre_cliente', models.CharField(max_length=32, null=True)),
                ('rut', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('direccion', models.CharField(max_length=64, null=True)),
                ('modo_entrega', models.CharField(max_length=64, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('total', models.IntegerField()),
                ('validado', models.BooleanField(default=False)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente de pago'), (2, 'Pagado'), (3, 'Rechazado'), (4, 'Anulado')], default=1)),
                ('producto', models.ManyToManyField(to='TocApp.producto')),
            ],
        ),
    ]
