# Generated by Django 4.1 on 2022-12-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TocApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreProd',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreTipo',
            field=models.CharField(choices=[('H', 'Hamburguesa'), ('C', 'Completo'), ('P', 'Pizza '), ('PF', 'Papas Fritas'), ('J', 'Jugo'), ('B', 'Bebida')], default='H', max_length=20),
        ),
    ]
