# Generated by Django 4.1.2 on 2022-12-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TocApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='combos',
            field=models.ManyToManyField(to='TocApp.combo'),
        ),
    ]
