# Generated by Django 4.1 on 2022-12-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TocApp', '0002_remove_producto_activo_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCombo', models.CharField(max_length=50)),
                ('precioCombo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComboProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TocApp.combo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TocApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='producto',
            field=models.ManyToManyField(through='TocApp.ComboProducto', to='TocApp.producto'),
        ),
    ]
