# Generated by Django 4.1 on 2022-12-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TocApp', '0003_combo_comboproducto_combo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10)),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('Cargo', models.CharField(choices=[('C', 'Cajero'), ('G', 'Gerente'), ('A', 'Aseo')], default='C', max_length=1)),
                ('Contrato', models.CharField(choices=[('P', 'Plazo Fijo'), ('I', 'Indefinido')], default='I', max_length=1)),
            ],
        ),
    ]
