# Generated by Django 4.1.2 on 2022-12-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TocApp', '0005_venta_ventaproducto_ventacombo_venta_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='anular',
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente de pago'), (2, 'Pagado'), (3, 'Rechazado'), (4, 'Anulado')], default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='modo_entrega',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='rut',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
